# Generated by Django 5.2 on 2025-04-24 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_userprofile_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='plaid_access_token',
            field=models.TextField(blank=True, null=True),
        ),
    ]
