# Generated by Django 5.0 on 2025-04-21 20:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='budget',
            old_name='date',
            new_name='date_created',
        ),
        migrations.RemoveField(
            model_name='budget',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='budget',
            name='name',
        ),
        migrations.AddField(
            model_name='budget',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Amount in your currency (e.g. 1234.56', max_digits=10),
        ),
        migrations.AddField(
            model_name='budget',
            name='category',
            field=models.CharField(blank=True, help_text="e.g. 'Groceries', 'Rent', 'Entertainment'", max_length=50),
        ),
        migrations.AddField(
            model_name='budget',
            name='description',
            field=models.TextField(blank=True, help_text='Optional description or notes'),
        ),
        migrations.AddField(
            model_name='budget',
            name='title',
            field=models.CharField(default='Untitled', help_text='A short name for this budget item', max_length=100),
        ),
        migrations.AddField(
            model_name='budget',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
