# Generated by Django 5.0 on 2025-04-21 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0002_rename_date_budget_date_created_remove_budget_cost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Amount in your currency (e.g. 1234.56)', max_digits=10),
        ),
    ]
