# Generated by Django 5.2 on 2025-04-23 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0006_alter_budget_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='category',
            field=models.CharField(choices=[('FOOD', 'Food'), ('RENT', 'Rent'), ('UTIL', 'Utilities'), ('TRAN', 'Transportation'), ('ENTR', 'Entertainment'), ('HEAL', 'Health'), ('MISC', 'Miscellaneous')], max_length=10),
        ),
    ]
